# Generated by Django 2.2.dev20181102145912 on 2018-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workspace_name', models.CharField(max_length=20)),
            ],
        ),
    ]
