# Generated by Django 2.2.dev20181102145912 on 2018-11-04 16:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20181104_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=20)),
                ('users', jsonfield.fields.JSONField(default=None)),
                ('messages', jsonfield.fields.JSONField(default=None)),
            ],
        ),
    ]
