# Generated by Django 2.2.dev20181102145912 on 2018-11-05 05:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='channels',
            field=jsonfield.fields.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='users',
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
