# Generated by Django 2.0.5 on 2018-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isfirst',
            field=models.BooleanField(default=True),
        ),
    ]
