# Generated by Django 2.2.dev20181102145912 on 2018-11-05 13:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=256)),
                ('workspaces', jsonfield.fields.JSONField(default=None)),
            ],
        ),
    ]
