# Generated by Django 2.2.dev20181102145912 on 2018-11-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='workspaces',
        ),
    ]
