# Generated by Django 2.2.dev20181102145912 on 2018-11-06 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='workspaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
