# Generated by Django 2.0.5 on 2018-11-11 15:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Workspaces', '0002_auto_20181111_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('replies', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('channels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workspaces.Channel')),
            ],
        ),
    ]
