# Generated by Django 2.0.5 on 2018-11-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_workspaces'),
        ('Workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(to='Users.User'),
        ),
        migrations.AddField(
            model_name='channel',
            name='workspaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workspaces.Workspace'),
        ),
    ]
