# Generated by Django 2.0.5 on 2018-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspaces', '0003_auto_20181111_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(to='Users.User'),
        ),
    ]
